# Generated by Django 3.2.4 on 2021-10-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Performance', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Caste', models.CharField(max_length=50)),
                ('Coaching', models.CharField(max_length=50)),
                ('time', models.IntegerField()),
                ('Class_ten_education', models.CharField(max_length=50)),
                ('twelve_education', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=50)),
                ('Class_X_Percentage', models.CharField(max_length=50)),
                ('Class_XII_Percentage', models.CharField(max_length=50)),
                ('Father_occupation', models.CharField(max_length=50)),
                ('Mother_occupation', models.CharField(max_length=50)),
            ],
        ),
    ]
